/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosesRouteImport } from './routes/diagnoses'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FingerprintsRouteImport } from './routes/fingerprints'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosesRoute = DiagnosesRouteImport.update({
  id: '/diagnoses',
  path: '/diagnoses',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintsRoute = FingerprintsRouteImport.update({
  id: '/fingerprints',
  path: '/fingerprints',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnoses': typeof DiagnosesRoute
  '/evaluation': typeof EvaluationRoute
  '/feedback': typeof FeedbackRoute
  '/fingerprints': typeof FingerprintsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnoses': typeof DiagnosesRoute
  '/evaluation': typeof EvaluationRoute
  '/feedback': typeof FeedbackRoute
  '/fingerprints': typeof FingerprintsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnoses': typeof DiagnosesRoute
  '/evaluation': typeof EvaluationRoute
  '/feedback': typeof FeedbackRoute
  '/fingerprints': typeof FingerprintsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnoses' | '/evaluation' | '/feedback' | '/fingerprints'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnoses' | '/evaluation' | '/feedback' | '/fingerprints'
  id:
    | '__root__'
    | '/'
    | '/diagnoses'
    | '/evaluation'
    | '/feedback'
    | '/fingerprints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosesRoute: typeof DiagnosesRoute
  EvaluationRoute: typeof EvaluationRoute
  FeedbackRoute: typeof FeedbackRoute
  FingerprintsRoute: typeof FingerprintsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnoses': {
      id: '/diagnoses'
      path: '/diagnoses'
      fullPath: '/diagnoses'
      preLoaderRoute: typeof DiagnosesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprints': {
      id: '/fingerprints'
      path: '/fingerprints'
      fullPath: '/fingerprints'
      preLoaderRoute: typeof FingerprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosesRoute: DiagnosesRoute,
  EvaluationRoute: EvaluationRoute,
  FeedbackRoute: FeedbackRoute,
  FingerprintsRoute: FingerprintsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
